### ISSUE TITLE
compile develop branch example

### ISSUE THREAD

**Issue by brucelane** [bakercp/ofxMaps#3]
Hi,
I managed to compile and run the sample of the master branch, great!

I then noticed the develop branch which seems to bring some good features: https://github.com/bakercp/ofxMaps/tree/develop

I downloaded lots of addons:
- ofxIO ( https://github.com/bakercp/ofxIO )
- ofxJSON ( https://github.com/bakercp/ofxJSON )
- ofxMaps ( https://github.com/bakercp/ofxMaps/tree/develop )
- ofxMediaType ( https://github.com/bakercp/ofxMediaType )
- ofxSpatialHash ( https://github.com/bakercp/ofxSpatialHash )
- ofxSSLManager ( https://github.com/bakercp/ofxSSLManager )
- ofxTaskQueue ( https://github.com/bakercp/ofxTaskQueue )
- ofxSQLiteCpp ( https://github.com/bakercp/ofxSQLiteCpp )
- ofxGeoServices ( https://github.com/bakercp/ofxGeoServices )
- ofxJSONRPC ( https://github.com/bakercp/ofxJSONRPC )
- ofxGeo ( https://github.com/bakercp/ofxGeo )
- ofxNetworkUtils ( https://github.com/bakercp/ofxNetworkUtils )
- ofxHTTP ( https://github.com/bakercp/ofxHTTP )

But I get some compilation errors on several addons like ofxNetworkUtils, ofxSQLiteCpp, etc.
Would be nice to have some help on which addon repos to use.
I use Visual Studio 2013 and oF_vs2013 repo
Thank you

**Comment by bakercp** [comment]
Hey @brucelane thanks for posting the question!

Sorry -- I haven't tested it much on VS yet.  Can you point to the URL branch you're using?  Also ... I just uninstalled VS2013 and installed VS2015 ... b/c the OF master master branch is just getting support for that in the last few days.  Have you tried it with the latest OF master branch and VS2015 by chance -- as that will be the quickest place for me to start debugging.  I definitely want to get this up and going pretty soon as I have more projects that employ this coming down the line.

**Comment by brucelane** [comment]
wow, I didn't know VS2015 was supported! great news!
I got VS2015 installed, I can try the OF master branch

**Comment by bakercp** [comment]
Yeah, VS2015 support just got merged a few days ago ... it may still be rough though, so any beta testing reports you have will help all of us get 0.9.0 out the door more quickly :)

**Comment by brucelane** [comment]
please let me know the progress of the compilation of ofxMaps on VS2015
I also plan to use it on raspberry pi 2, mobile (android, ios, windows phone) is it possible?
thank you

**Comment by bakercp** [comment]
I'm taking a look at this today ...

**Comment by bakercp** [comment]
Hey @brucelane I'm moving along on this, but ran into a bunch of related things that had to be fixed because master dropped Poco support, etc.  I need this for upcoming projects too, so hang tight and hopefully I'll have something working in the next day or so.

**Comment by brucelane** [comment]
thank you, it seems there's a lot to do!

**Comment by bakercp** [comment]
Getting closer.  I've got it working with the master branch now but there's a big memory leak that has to do with Poco's old pointers and the new c++11 approach ... I'm investigating it this morning.

**Comment by bakercp** [comment]
OK!  I've got it all compiling on VS2015 ... but for some reason, which is still a mystery to me it seems to get super sluggish and hang ... I'm not sure where the bottleneck is as I'm less familiar with VS2015 profiling tools.  Perhaps you could download the latest ofxMaps devel, grab all of the dependencies (many of which have been updated on their develop branches as well) and see what you can make of it?  It's working nicely on OSX, if that makes a difference !

**Comment by bakercp** [comment]
Strike that ... it is working ... just looking into where the code was slow now.

**Comment by bakercp** [comment]
OK.  This is just a note to myself -- but for some reason a big slowdown is in ofx::HTTP::ClientResponseProgressArgs::getContentLength().  Each time it is called it actually goes back into the original response headers and iterates through a list of headers and then converts the string values to ints to return.  Not sure why this is so much slower on windows, but anyway, it's pretty inefficient as the response content length shouldn't change and could be cached in this case.

Anyway, it's on my todo list ...

**Comment by brucelane** [comment]
great! I'm doing to check all this develop branches and let you know

**Comment by brucelane** [comment]
I tryed to compile the example, adding ofxGeo(master) and ofxHTTP(develop), but I get plenty of errors... what are the addons needed and in what branch? could you add the sln/vcxproj files in the example folder? thank you

**Comment by bakercp** [comment]
What else are you getting? Did you regenerate the project files with the updated addons and project generator?

**Comment by bakercp** [comment]
Else = errors (typing on phone)

**Comment by brucelane** [comment]
example errors:
M_PI, M_E : undeclared identifiers
 'load' : is not a member of 'ofImage_<unsigned char>'  F:\openFrameworks\openFrameworks-VS2013\addons\ofxMaps\libs\ofxMaps\includes\ofx\Maps\BaseURITileProvider.h 65  

and is the list of ofxAddons I put in my first post of this issue correct?

**Comment by brucelane** [comment]
any update on this?
thank you
Bruce

**Comment by brucelane** [comment]
example error in coordinate.h, no conversion available :
inline std::ostream& operator<<(std::ostream& os, const Coordinate& coordinate)
{
    os << coordinate.toString();
    return os;
}

**Comment by brucelane** [comment]
yay!
![yaymaps](https://cloud.githubusercontent.com/assets/138158/9132185/e8e983b2-3cf1-11e5-8cf8-351368529f14.JPG)

**Comment by phaseIV** [comment]
Yes! Thank you very much bakercp, the develop branch is working for me too. Great stuff.
One question, if you don't mind; in the (0.8.4) master branch I could draw geolocations on the map like this:
ofVec2f drawlocation =  map.geoLocationToPoint(GeoLocation(52.340232, 4.944732));
ofCircle(drawlocation.x, drawlocation.y,20);

What would be the correct way to do this in the develop branch?

**Comment by bakercp** [comment]
Great question @phaseIV it looks like there was currently no way to access the projection data from the layer -- so I just added an accessor to the provider.  So you should be able to do something like

``` cpp

    layer->getProvider()->tileToGeo(...);
    layer->getProvider()->geoToTile(...);
```

This is all a work in progress ... !

**Comment by bakercp** [comment]
Closing this original issue now as it seems to be working.

**Comment by phaseIV** [comment]
Thank you so much for the fast reply and the additional code. Unfortunately the geoToTile doesn't work for me as it returns a static location that isn't moving or zooming when the map is moved.
Anyway, no worries, especially since the code is in progress/beta/develop stage. I can continue work with the 0.8.4 branch for now.
