### ISSUE TITLE
ofx/Cache missing?

### ISSUE THREAD

**Issue by egradman** [bakercp/ofxMaps#4]
Hi there.

I'm pretty close to getting your develop branch to compile!  Two (probably related) errors:
- Can't find `ofxCache.h`
- No `libs/ofx/Cache` directory

Any thoughts?  I'm on osx and openframeworks HEAD.  Thanks!

**Comment by faaip** [comment]
I'd love to try the develop branch, but I'm running in to the same issue. Have you figured it out @egradman ?

**Comment by harunali** [comment]
I'm running in to the same issue. It is not possible to find ofxCache came on !!!! @bakercp

**Comment by willgeary** [comment]
I am also very interested in the compiling this library... any chance there is an update? :)

**Comment by bakercp** [comment]
It lives here until i get time to update it ... https://github.com/bakercp/ofxCache/tree/develop
