### ISSUE TITLE
fix exception on missing path.

### ISSUE THREAD

**Issue by bakercp** [bakercp/ofxMaps#8]
Although I get a runtime error.
If the cache path doesn't exist (the folder structure) the app crashes at https://github.com/bakercp/ofxSQLiteCpp/blob/master/libs/SQLiteCpp/src/Database.cpp#L86
printing out this

SQLite::Exception SQLITE_CANTOPEN  
libc++abi.dylib: terminating with uncaught exception of type SQLite::Exception: unable to open database file
It is supposed to create the file if it doesn't exist but it doesn't create the folder structure if missing. I can fix it easily with ofFile::exists() but you might have a better solution.
BTW, I also had this problem with what I PR'd.

@roymacdonald

**Comment by roymacdonald** [comment]
Awesome! thanks
