### ISSUE TITLE
call of overloaded ‘bind(const char [13], int64_t)’ is ambiguous

### ISSUE THREAD

**Issue by ghost** [bakercp/ofxMaps#9]
Hi,
I want to compile the example. I'm getting a bunch of errors like the one below.

Do I need some compile flag for this?

My system:
Ubuntu 16.04
OF 010

```
/mnt/FILES/CODE/OF/OF_100_64B/addons/ofxMaps/libs/ofxMaps/src/MBTilesCache.cpp:459:56: error: call of overloaded ‘bind(const char [13], int64_t)’ is ambiguous
             selectMap.bind(":tile_column", key.column());

/mnt/FILES/CODE/OF/OF_100_64B/addons/ofxMaps/libs/ofxMaps/src/MBTilesCache.cpp:460:50: error: call of overloaded ‘bind(const char [10], int64_t)’ is ambiguous
             selectMap.bind(":tile_row", key.row());
```

**Comment by bakercp** [comment]
I can confirm the issue.

The latest version of [SQLiteCPP](https://github.com/SRombauts/SQLiteCpp/releases/tag/2.3.0) fixes this ambiguous binding issue on linux.  I updated [ofxSQliteCPP](https://github.com/bakercp/ofxSQLiteCpp) to include the updated version and it now compiles for me on Ubuntu16.04/oF 010.  Please reopen if there are still issues.

**Comment by ghost** [comment]
yup, thx, is working now

**Comment by bakercp** [comment]
Cool.  Keep me posted.  Curious to see what you do with it!
